# Gradle
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true
kotlin.mpp.enableCInteropCommonization=true

# Android
android.useAndroidX=true

# Gobley
gobley.projects.gradleTests=false
gobley.projects.uniffiTests=false
gobley.projects.uniffiTests.extTypes=false
gobley.projects.uniffiTests.futures=false
gobley.projects.examples.app=false
gobley.projects.examples.audioCppApp=false
gobley.projects.examples.customTypes=false
gobley.projects.examples.tokioBlake3App=false
gobley.projects.examples.tokioBoringApp=true