name: Build and run tests

on:
  push:
    branches: [ "main*" ]
  pull_request:
    branches: [ "main*" ]

jobs:
  build-and-test:
    name: Build and run unit tests
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        test-name:
          - cargo-tests
          - examples
          - gradle-plugin-tests
          - gradle-tests
          - uniffi-tests
        os:
          - windows
          - macos
          - linux
        include:
          # cargo-tests -> normal runners
          - test-name: cargo-tests
            os: windows
            runner: windows-latest
          - test-name: cargo-tests
            os: macos
            runner: macos-latest
          - test-name: cargo-tests
            os: linux
            runner: ubuntu-latest
          # examples -> large runners on macOS
          # macOS examples need to build iOS, tvOS, and watchOS, resulting in a significant build time
          - test-name: examples
            os: windows
            runner: windows-latest
          - test-name: examples
            os: macos
            runner: macos-latest-xlarge
          - test-name: examples
            os: linux
            runner: ubuntu-latest
          # gradle-plugin-tests -> normal runners
          - test-name: gradle-plugin-tests
            os: windows
            runner: windows-latest
          - test-name: gradle-plugin-tests
            os: macos
            runner: macos-latest
          - test-name: gradle-plugin-tests
            os: linux
            runner: ubuntu-latest
          # gradle-tests -> normal runners
          - test-name: gradle-tests
            os: windows
            runner: windows-latest
          - test-name: gradle-tests
            os: macos
            runner: macos-latest
          - test-name: gradle-tests
            os: linux
            runner: ubuntu-latest
          # uniffi-tests -> large runners on Windows & macOS
          # FuturesTest fails a lot on standard Windows and macOS runners
          - test-name: uniffi-tests
            os: windows
            runner: windows-latest-x64-large
          - test-name: uniffi-tests
            os: macos
            runner: macos-latest-xlarge
          - test-name: uniffi-tests
            os: linux
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v4
      - name: Install Zig
        shell: pwsh
        run: ./.github/workflows/pr-build-test/dependencies-zig.ps1
      - name: Install dependencies
        shell: pwsh
        run: ./.github/workflows/pr-build-test/dependencies.ps1
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up the Android SDK
        uses: android-actions/setup-android@v3
      - name: Install additional required Android SDK packages and configure environment variables
        shell: pwsh
        run: |
          sdkmanager --install "ndk;27.0.12077973"
          "ANDROID_HOME=${env:ANDROID_SDK_ROOT}" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Run tests
        shell: pwsh
        run: ./.github/workflows/pr-build-test/${{ matrix.test-name }}.ps1
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ matrix.test-name != 'cargo-tests' && (success() || failure()) }}
        with:
          name: junit-test-results-${{ matrix.test-name }}-${{ matrix.os }}
          path: './.github/workflows/pr-build-test/test-results/**/*est/TEST-*.xml'
          retention-days: 1